app_admin:
    resource: "@AppBundle/Resources/config/routing/configuracion.yml"
    prefix:   /admin/

welcome:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

adminStart:
    path:     /admin/adminstart
    defaults: { _controller: AppBundle:Default:adminStart }

#pageNotFound:
#    path:  /{path}
#    defaults: { _controller: AppBundle:Default:pageNotFound, path: '' }
#    requirements:
#        path: .*

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin/sonata

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin/sonata

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /admin/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /admin/media

horariosStart:
    path:     /horario/{area}
    defaults: { _controller: AppBundle:Default:horarioStart }
